update from upstream

diff --git a/applications/luci-app-frpc/root/etc/init.d/frp b/applications/luci-app-frpc/root/etc/init.d/frp
--- a/applications/luci-app-frpc/root/etc/init.d/frp
+++ b/applications/luci-app-frpc/root/etc/init.d/frp
@@ -2,8 +2,9 @@
 #Author: monokoo <realstones2012@gmail.com>
 #Thanks to FW867's help
 
-USE_PROCD=1
 START=99
+SERVICE_WRITE_PID=1
+SERVICE_DAEMONIZE=1
 
 LOGFILE="/var/etc/frp/frpc.log"
 
@@ -30,7 +31,7 @@ conf_proxy_add() {
 	local tmpconf="$2"
 	local enable type domain_type custom_domains remote_port local_ip local_port enable_http_auth enable_host_header_rewrite host_header_rewrite
 	local subdomain proxy_protocol_version use_encryption use_compression http_user http_pwd remark locations
-	local enable_plugin plugin plugin_http_user plugin_http_passwd plugin_unix_path stcp_role stcp_secretkey stcp_servername
+	local enable_plugin plugin plugin_http_user plugin_http_passwd plugin_unix_path stcp_role stcp_secretkey stcp_servername xtcp_role xtcp_secretkey xtcp_servername
         local enable_https_plugin https_plugin plugin_local_addr plugin_crt_path plugin_key_path plugin_host_header_rewrite plugin_header_X_From_Where
 	
 	config_get_bool enable "$cfg" enable 1
@@ -54,6 +55,9 @@ conf_proxy_add() {
 	config_get stcp_role "$cfg" stcp_role
 	config_get stcp_secretkey "$cfg" stcp_secretkey
 	config_get stcp_servername "$cfg" stcp_servername
+	config_get xtcp_role "$cfg" xtcp_role
+	config_get xtcp_secretkey "$cfg" xtcp_secretkey
+	config_get xtcp_servername "$cfg" xtcp_servername
 	config_get proxy_protocol_version "$cfg" proxy_protocol_version
 	config_get https_plugin "$cfg" https_plugin
 	config_get plugin_local_addr "$cfg" plugin_local_addr
@@ -71,8 +75,8 @@ conf_proxy_add() {
 	[ -n "$custom_domains" ] && echo "custom_domains=$custom_domains" >>$tmpconf
 	[ -n "$subdomain" ] && echo "subdomain=$subdomain" >>$tmpconf
 	[ -n "$remote_port" ] && echo "remote_port=$remote_port" >>$tmpconf
-	[ -z "$stcp_role" ] && [ -n "$local_ip" ] && echo "local_ip=$local_ip" >>$tmpconf
-	[ -z "$stcp_role" ] && [ -n "$local_port" ] && echo "local_port=$local_port" >>$tmpconf
+	[ -z "$stcp_role" ] && [ -z "$xtcp_role" ] && [ -n "$local_ip" ] && echo "local_ip=$local_ip" >>$tmpconf
+	[ -z "$stcp_role" ] && [ -z "$xtcp_role" ] && [ -n "$local_port" ] && echo "local_port=$local_port" >>$tmpconf
 	[ -n "$locations" ] && echo "locations=$locations" >>$tmpconf
 	[ -n "$http_user" -a -n "$http_pwd" ] && {
 		echo "http_user=$http_user" >>$tmpconf
@@ -97,6 +101,19 @@ conf_proxy_add() {
 			[ -n "$local_port" ] && echo "local_port=$local_port" >>$tmpconf
 		fi
 		[ -n "$stcp_secretkey" ] && echo "sk=$stcp_secretkey" >>$tmpconf || return 1
+	}
+	
+	[ -n "$xtcp_role" ] && {
+		if [ "$xtcp_role" == "visitor" ]; then
+			echo "role=$xtcp_role" >>$tmpconf
+			[ -n "$local_ip" ] && echo "bind_addr=$local_ip" >>$tmpconf
+			[ -n "$local_port" ] && echo "bind_port=$local_port" >>$tmpconf
+			[ -n "$xtcp_servername" ] && echo "server_name=$xtcp_servername" >>$tmpconf || return 1
+		else
+			[ -n "$local_ip" ] && echo "local_ip=$local_ip" >>$tmpconf
+			[ -n "$local_port" ] && echo "local_port=$local_port" >>$tmpconf
+		fi
+		[ -n "$xtcp_secretkey" ] && echo "sk=$xtcp_secretkey" >>$tmpconf || return 1
 	}
 	
 	[ -n "$proxy_protocol_version" ] && {
@@ -133,10 +150,46 @@ frp_write_bool() {
 	fi
 }
 
-start_service() {
+frp_add_cru(){
+time=$1
+if [ ! -f "/etc/crontabs/root" ] || [ -z "$(cat /etc/crontabs/root | grep frp)" ]; then
+  sed -i '/frp/d' /etc/crontabs/root >/dev/null 2>&1
+  echo "*/$time * * * * /etc/init.d/frp restart" >> /etc/crontabs/root 
+fi
+
+}
+
+frp_del_cru(){
+if [ ! -f "/etc/crontabs/root" ] || [ -n "$(cat /etc/crontabs/root | grep frp)" ]; then
+  sed -i '/frp/d' /etc/crontabs/root >/dev/null 2>&1
+fi
+}
+
+download_binary(){
+	echo_date "开始下载frpc二进制文件..."
+	/usr/bin/wget --no-check-certificate --timeout=10 --tries=1 -o $LOGFILE https://github.com/fatedier/frp/releases/download/v0.13.0/frp_0.13.0_linux_arm.tar.gz -O /tmp/frp_0.13.0_linux_arm.tar.gz
+	[ ! -s "/tmp/frp_0.13.0_linux_arm.tar.gz" ] && /usr/bin/wget -q --no-check-certificate --timeout=10 --tries=1 https://any.mokoo.xyz/app/frp_0.13.0_linux_arm.tar.gz -O /tmp/frp_0.13.0_linux_arm.tar.gz
+	[ -f "/tmp/frp_0.13.0_linux_arm.tar.gz" ] && tar -xf /tmp/frp_0.13.0_linux_arm.tar.gz -C /tmp && \
+		mv /tmp/frp_0.13.0_linux_arm/frpc /usr/bin/frpc
+	rm -rf /tmp/frp_0.13.0_linux_arm*
+	if [ -f "/usr/bin/frpc" ]; then
+		chmod +x /usr/bin/frpc && echo_date "成功下载frpc二进制文件"
+	else
+		echo_date "下载frpc二进制文件失败，请重试！"
+	fi
+}
+
+boot() {
+	sleep 10s
+	start
+}
+
+start() {
+
 	config_load "frp"
-	local enabled server_addr server_port privilege_token user tcp_mux enable_cpool tls_enable
+	local enabled server_addr server_port time privilege_token user tcp_mux enable_cpool tls_enable
 	local pool_count log_level log_max_days login_fail_exit http_proxy protocol admin_port admin_user admin_pwd
+	local tls_cert_file tls_key_file tls_trusted_ca_file
 
 	config_get_bool enabled common enabled 1
 
@@ -152,16 +205,21 @@ start_service() {
 	config_get log_max_days common log_max_days
 	config_get http_proxy common http_proxy
 	config_get protocol common protocol
+	config_get time common time
 	config_get admin_port common admin_port
 	config_get admin_user common admin_user
 	config_get admin_pwd common admin_pwd
+	config_get tls_cert_file common tls_cert_file
+	config_get tls_key_file common tls_key_file
+	config_get tls_trusted_ca_file common tls_trusted_ca_file
 
 
 	mkdir -p /var/etc/frp
-	[ -f "$LOGFILE" ] || touch $LOGFILE
+	[ ! -f "$LOGFILE" ] && touch $LOGFILE
 	
-	[ -e "/usr/bin/frpc" ] || ( logger -t Frp 'frpc not found.'; exit 1; )
-
+	[ ! -f "/usr/bin/frpc" ] && download_binary
+	[ ! -f "/usr/bin/frpc" ] && logger -t Frp 'Download frpc failed, please retry.' && exit 0
+	
 	local tmpconf="/var/etc/frp/frpc.conf"
 
 	echo "[common]" >$tmpconf
@@ -178,32 +236,33 @@ start_service() {
 	[ -n "$admin_port" ] && echo "admin_addr=0.0.0.0" >>$tmpconf && echo "admin_port=$admin_port" >>$tmpconf
 	[ -n "$admin_user" ] && echo "admin_user=$admin_user" >>$tmpconf
 	[ -n "$admin_pwd" ] && echo "admin_pwd=$admin_pwd" >>$tmpconf
+	[[ -n "$tls_cert_file" && -n "$tls_key_file" ]] && echo "tls_cert_file=$tls_cert_file" >>$tmpconf && echo "tls_key_file=$tls_key_file" >>$tmpconf
+	[ -n "$tls_trusted_ca_file" ] && echo "tls_trusted_ca_file=$tls_trusted_ca_file" >>$tmpconf
 
+
+	config_load "frp"
 	frp_write_bool tcp_mux common 1
 	frp_write_bool tls_enable common 0
 	frp_write_bool login_fail_exit common 1
 	config_foreach conf_proxy_add proxy "$tmpconf"
 
-	[ "$(cat "$tmpconf" | grep -c "type=")" -gt 0 ] || ( echo_date "frp服务启动失败，请首先添加服务列表！"; exit 0; )
+	[ "$(cat "$tmpconf" | grep -c "type=")" -gt 0 ] || (echo_date "frp服务启动失败，请首先添加服务列表！" && exit 0)
 	logger -t FRPC 'Starting frp service'
+	SERVICE_DAEMONIZE=1 \
+		service_start /usr/bin/frpc -c $tmpconf
 
-	procd_open_instance frp
-	procd_set_param command /usr/bin/frpc
-	procd_append_param command -c $tmpconf
-	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-10}
-	procd_close_instance
+	[ "$time" -gt 0 ] && frp_add_cru $time
+	[ -z "$(pgrep /usr/bin/frpc)" ] && echo_date "frp服务启动失败，请检查服务端 “TCP多路复用(tcp_mux)”设置，确保与客户端完全一致！"
+
+	return 0
 }
 
-stop_service() {
-	logger -t FRPC 'Shutting down frp service'
-	Reduce_Log $LOGFILE
-}
-
-reload_service() {
-	stop
-	start
-}
-
-service_triggers() {
-	procd_add_reload_trigger "frp"
+stop() {
+	frp_del_cru
+	if [ -n "`pidof frpc`" ]; then
+		logger -t FRPC 'Shutting down frp service'
+		service_stop /usr/bin/frpc
+		Reduce_Log $LOGFILE
+	fi
+	return 0
 }
